### ISSUE TITLE
There is no monocular_mesh_dataset.py

### ISSUE THREAD

**Issue by Heloworkdl** [zju3dv/neuralbody#31]
I need monocular_mesh_dataset.py when running custom data.  However, the file cannot be found.  Please confirm. Thanks.

**Comment by pengsida** [comment]
I have fixed the bug.

**Comment by Heloworkdl** [comment]
When I run custom, I still get the same bug.  Is there anything I need to correct?

**Comment by pengsida** [comment]
You need to git pull the code.
